version: "3"
services:
    jobs_db:
        image: postgres:12.0-alpine
        container_name: jobs_db
        environment:
            - POSTGRES_DB=jobs
            - POSTGRES_USER=jobs_user
            - POSTGRES_PASSWORD=jobs_#*9adnje2
            - POSTGRES_HOST=jobs_db
        expose:
            - "5432"
        volumes:
            - db_data:/var/lib/postgresql/data
    redis:
        image: redis:4.0.1
        container_name: jobs_redis
        restart: unless-stopped
        command: redis-server
        expose:
            - "6379"
    celery:
        build:
            context: .
            dockerfile: ./compose/celery/Dockerfile
        container_name: jobs_celery
        restart: unless-stopped
        # volumes:
        #     - ./djangoapps:/app/src/
        links:
            - jobs_db
        depends_on:
            - redis
        environment:
            - ENVIRONMENT
            - LOCAL_RUN=0
        env_file:
            - ./.env.dev
    celery-beat:
        build:
            context: .
            dockerfile: ./compose/celery_beat/Dockerfile
        container_name: jobs_celery_beat
        # volumes:
        #     - ./djangoapps:/app/src/
        depends_on:
          - redis
        environment:
            - ENVIRONMENT
            - LOCAL_RUN=0
        env_file:
            - ./.env.dev
    web:
        build:
            context: .
            dockerfile: ./compose/web/Dockerfile.dev
        container_name: web
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
          - ./.env.dev
        # volumes:
        #     - ./djangoapps:/app/src/
        depends_on:
            - jobs_db
volumes:
    db_data: {}
